package models

import (
	_ "github.com/yurivict/ollama/model/models/bert"
	_ "github.com/yurivict/ollama/model/models/deepseek2"
	_ "github.com/yurivict/ollama/model/models/deepseekocr"
	_ "github.com/yurivict/ollama/model/models/gemma2"
	_ "github.com/yurivict/ollama/model/models/gemma3"
	_ "github.com/yurivict/ollama/model/models/gemma3n"
	_ "github.com/yurivict/ollama/model/models/gemma4"
	_ "github.com/yurivict/ollama/model/models/glm4moelite"
	_ "github.com/yurivict/ollama/model/models/glmocr"
	_ "github.com/yurivict/ollama/model/models/gptoss"
	_ "github.com/yurivict/ollama/model/models/laguna"
	_ "github.com/yurivict/ollama/model/models/lfm2"
	_ "github.com/yurivict/ollama/model/models/llama"
	_ "github.com/yurivict/ollama/model/models/llama4"
	_ "github.com/yurivict/ollama/model/models/mistral3"
	_ "github.com/yurivict/ollama/model/models/mllama"
	_ "github.com/yurivict/ollama/model/models/nemotronh"
	_ "github.com/yurivict/ollama/model/models/nomicbert"
	_ "github.com/yurivict/ollama/model/models/olmo3"
	_ "github.com/yurivict/ollama/model/models/qwen2"
	_ "github.com/yurivict/ollama/model/models/qwen25vl"
	_ "github.com/yurivict/ollama/model/models/qwen3"
	_ "github.com/yurivict/ollama/model/models/qwen3next"
	_ "github.com/yurivict/ollama/model/models/qwen3vl"
)
